config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'users#login'
  post '/login' => 'users#save'
  get '/tokens/out' => 'tokens#out', :as => 'tokens_out'
  get '/tokens/in' => 'tokens#in', :as => 'tokens_in'
  get '/reset' => 'tokens#reset'
  get '/tokens' => 'tokens#index', :as => 'tokens'
  post '/tokens' => 'tokens#create'
  get '/tokens/new' => 'tokens#new', :as => 'new_token'
  get '/tokens/save' => 'tokens#save', :as => 'save_token'
  get '/tokens/:id/edit' => 'tokens#edit', :as => 'edit_tokens'
  get '/tokens/:id' => 'tokens#show', :as => 'token'
  patch '/tokens/:id' => 'tokens#update'
  put '/tokens/:id' => 'tokens#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :token
  validates_presence_of :subject, :request
end

app/models/recipient.rb
class Recipient < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :state
  belongs_to :recipient
  has_one :package, inverse_of: :token, dependent: :destroy
  accepts_nested_attributes_for :package, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tokens_controller.rb
#
class TokensController < ApplicationController
  before_action :set_token, only: [:show, :edit, :update, ]

  # GET /tokens
  def index
    @user = session[:user]
    @tokens = Token.all
  end

  # GET /tokens/1
  def show
    @user = session[:user]
  end

  def out
    @user = session[:user]
    @tokens = Token.where("creator = '#{@user}' and state_id <> '#{ARCHIVED.id}'")
                  .order('state_id')
  end

  def in
    @user = session[:user]
    @id = session[:user_id]
    @tokens = Token.where("recipient_id = '#{@id}' and state_id <> '#{ARCHIVED.id}'")
                  .order('state_id')
  end

  # GET /tokens/new
  def new
    @user = session[:user]
    @token = Token.new
    @token.build_package
  end


  def edit
    @user = session[:user]
  end

  # POST /tokens
  def create
    @token = Token.new(token_params)
    @token.creator = session[:user]
    @token.state = State.find_by_name('draft')

    if @token.save
      redirect_to @token, notice: 'Token was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tokens/1
  def update
    if @token.update(token_params)
      redirect_to @token, notice: 'Token was successfully updated.'
    else
      render :edit
    end
  end

  def reset
    config = ActiveRecord::Base.connection.adapter_name.downcase.to_sym
    case config
    when :sqlite
      ActiveRecord::Base.connection.execute('DELETE FROM packages')
      ActiveRecord::Base.connection.execute("DELETE FROM sqlite_sequence WHERE name='packages'")
      ActiveRecord::Base.connection.execute('DELETE FROM tokens')
      ActiveRecord::Base.connection.execute("DELETE FROM sqlite_sequence WHERE name='tokens'")

    when :postgresql
      ActiveRecord::Base.connection.execute('DELETE FROM packages')
      ActiveRecord::Base.connection.execute('ALTER SEQUENCE packages_id_seq RESTART WITH 1')
      ActiveRecord::Base.connection.execute('DELETE FROM tokens')
      ActiveRecord::Base.connection.execute('ALTER SEQUENCE tokens_id_seq RESTART WITH 1')

    end

  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_token
    @token = Token.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def token_params
    params.require(:token).permit(:id, :state_id, :recipient_id,
                                  package_attributes: [:id, :subject, :request, :response])
  end
end

app/controllers/users_controller.rb
#
class UsersController < ApplicationController
  def login
  end

  def save
    user_id = params[:user][:id]
    @user = Recipient.find_by_id(user_id).name
    session[:user] = @user
    session[:user_id] = user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tokenboots</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <h2>Tokens</h2>

      <div class="row">
        <div class="col-sm-9">
          <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link active" href="/tokens/new">New Token</a> |
                <a class="nav-item nav-link" href="/tokens/out">Outgoing Tokens </a> |
                <a class="nav-item nav-link" href="/tokens/in">Incoming Tokens   </a>
                <% if @user %>
                    | <a class="nav-item nav-link" href="/login">Current User : <%= @user %> </a>
                <% end %>
              </div>
            </div>
          </nav>
          <%= image_tag("token.png", width: 128, height: 128, :alt => "token") %>
          <%= yield %>
        </div>
        <div class="col-sm-3">
          <div class="sidebar">
            <h4>News</h4>
           </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tokens/_edit_form.html.erb
<%= semantic_form_for @token do |f| %>

  <%= f.semantic_fields_for :package do |package| %>
    <%= render 'edit_package', :f => package %>
  <% end %>
  <% if @token.creator != @user %>
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
    <label class="btn btn-info btn-sm">
      <input id="token_state_id_3"  type="radio" value="3" name="token[state_id]">accept
    </label>
    <label class="btn btn-warning btn-sm">
      <input id="token_state_id_4"  type="radio" value="4" name="token[state_id]">reject
    </label>
    <label class="btn btn-success btn-sm">
      <input id="token_state_id_5"  type="radio" value="5" name="token[state_id]">complete
    </label>
    </div>
  <% else %>
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
      <label class="btn btn-success btn-sm">
        <input id="token_state_id_2"  type="radio" value="2" name="token[state_id]">send
      </label>
      <label class="btn btn-warning btn-sm">
        <input id="token_state_id_6"  type="radio" value="6" name="token[state_id]">cancel
      </label>
      <label class="btn btn-info btn-sm">
        <input id="token_state_id_7"  type="radio" value="7" name="token[state_id]">archive
      </label>
    </div>
  <% end %>
  <br><br>
  <%= f.actions do %>
    <%= f.action :submit, :button_html => {:class => "btn btn-primary btn-lg" }, :label => 'Update'  %>
  <% end %>
<% end %>

app/views/tokens/_edit_package.html.erb
<h5 class="text-success">Token Subject : <%= @token.package.subject %><br><br>
<p class="text-info">Current State : <span class="btn btn-warning"><%= @token.state.name %></span></p></h5>
<div class='nested-fields'>
<%= f.inputs do %>
  <%= f.input :request, :as => :text, :input_html => {:class => "auto grow", :rows => 5, :cols => 80}%>
  <%= f.input :response, :required => false,
              :as => :text, :input_html => {:class => "auto grow", :rows => 5, :cols => 80} %>
<% end %>
</div>

app/views/tokens/_new_package.html.erb
<div class='nested-fields'>
  <%= f.inputs do %>
  <%= f.input :subject, :label => "Token Subject", :collection => SUBJECTS %>
  <%= f.input :request, :as => :text, :input_html => {:class => "auto grow", :rows => 5, :cols => 80}%>
  <%= f.input :response, :required => false,
              :as => :text, :input_html => {:class => "auto grow", :rows => 5, :cols => 80} %>
    <% end %>
</div>

app/views/tokens/_new_token.html.erb
<%= semantic_form_for @token do |f| %>
  <%= f.semantic_fields_for :package do |package| %>
    <%= render 'new_package', :f => package %>
  <% end %>
  <%= f.inputs do %>
    <%= f.input :recipient %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/tokens/edit.html.erb
<h4>Editing Token created by <%= @user %></h4>
<%= render 'edit_form', token: @token %>

app/views/tokens/in.html.erb
<p id="notice"><%= notice %></p>

<h3>Incoming Tokens for <%= @user %></h3>

<table class=table table-striped>
  <thead>
    <tr>
      <th>State</th>
      <th>Creator</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.state.name %></td>
        <td><%= token.creator %></td>
        <td><%= token.package.subject %></td>
        <td><%= link_to 'Show', token %></td>
        <td><%= link_to 'Edit', edit_tokens_path(token)  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tokens</h1>

<table>
  <thead>
    <tr>
      <th>Creator</th>
      <th>Package</th>
      <th>State</th>
      <th>Recipient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.creator %></td>
        <td><%= token.package %></td>
        <td><%= token.state %></td>
        <td><%= token.recipient %></td>
        <td><%= link_to 'Show', token %></td>
        <td><%= link_to 'Edit', edit_token_path(token) %></td>
        <td><%= link_to 'Destroy', token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Token', new_token_path %>

app/views/tokens/new.html.erb
<h2>New outgoing Token</h2>
<%= render 'new_token', token: @token %>

app/views/tokens/out.html.erb
<p id="notice"><%= notice %></p>

<h3>Outgoing Tokens created by <%= @user %></h3>

<table class=table table-striped>
  <thead>
    <tr>
      <th>State</th>
      <th>Recipient</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.state.name %></td>
        <td><%= token.recipient.name %></td>
        <td><%= token.package.subject %></td>
        <td><%= link_to 'Show', token %></td>
        <td><%= link_to 'Edit', edit_tokens_path(token) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tokens/reset.html.erb
DataBase Reset

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p class="text-primary">
  <strong>Creator:</strong>
  <%= @token.creator %>
</p>

<p class="text-primary">
  <strong>State:</strong>
  <%= @token.state.name %>
</p>

<p class="text-primary">
  <strong>Recipient:</strong>
  <%= @token.recipient.name %>
</p>
<div class="list-group">
  <ul>
    <li class="list-group-item list-group-item-success">Subject: <%= @token.package.subject %></li>
    <li class="list-group-item list-group-item-warning">Request: <%= @token.package.request %></li>
    <li class="list-group-item list-group-item-info"> Response: <%= @token.package.response %></li>
  </ul>
</div>

app/views/users/login.html.erb
<%= bootstrap_form_for :user do |f| %>
  <%= f.collection_select(:id, Recipient.order('name ASC').all, :id, :name, :label => 'User name',
                          :prompt => 'Select name') %>
  <%= f.submit "Enter", :class => "btn btn-success"%>
<% end %>

app/views/users/save.html.erb
<h3>Selected user :  <%= @user %></h3>